### ISSUE TITLE
consider exporting the number parser as its own library

### ISSUE THREAD

**Issue by lemire** [ezrosent/frawk#20]
It might be useful to export the number parsing module as a reusable library.

**Comment by ezrosent** [comment]
Agreed! (and thanks for those routines, by the way!)  I haven't done this to start with because most of the number parsing routines for Rust return an option, rather than stopping early and/or returning 0 like Awk does. Still, I suspect it wouldn't be too much additional work to implement both in a separate crate and expose it, so I'll keep this issue open for now.

**Comment by ezrosent** [comment]
It seems someone beat me to it! I'm going to close this issue in light of the release of the new (and excellent) [fast-float-rust](https://github.com/aldanor/fast-float-rust) library. I've actually switched frawk over to using that as well (#46)

**Comment by lemire** [comment]
I am sure @aldanor will be happy.

**Comment by aldanor** [comment]
> I suspect it wouldn't be too much additional work to implement both in a separate crate and expose it

It happened to be quite a lot of additional work :)

Glad it came useful here!

**Comment by lemire** [comment]
> It happened to be quite a lot of additional work :)

:-)

**Comment by ezrosent** [comment]
Thanks again to both of you!
