### ISSUE TITLE
Feature request: Parse the header-line

### ISSUE THREAD

**Issue by asayers** [ezrosent/frawk#31]
Given foobar.csv:

```csv
foo,bar
1,2
3,4
```

I'd like to be able to write bar_mean.awk:

```awk
{ acc += FIELDS["bar"] }
END { print "bar's mean is " acc/NR }
```

and run it like this:

```
$ frawk -icsv --headers -f bar_mean.awk <foobar.csv
bar's mean is 3
```

Differences when `--headers` is passed:

* The first line is skipped: it's neither processed by the awk program, nor does it count towards `NR`.
* A magic hashmap is defined (I called it `FIELDS` for the sake of the example above) which maps header name to field value.

If you're open to going crazy with the syntax, you could even do something like `$"bar"`.  (I think `$bar` is probably going too far, since that's already valid AWK.)

**Comment by asayers** [comment]
Open question: what to do about duplicate headers?  It's probably fine to do something arbitrary, and maybe issue a warning.

Anyway, I think this would be a really cool feature to have!  What do you guys think?

**Comment by ezrosent** [comment]
Hi! 

Thanks for reaching out. I do think it makes sense to do. Utilities like xsv and tsv-utils have facilities for parsing headers and referencing fields by name, and the equivalent in frawk today would be to do something like:

```awk 
NR == 1 { for (i=1; i<=NF; i++) { FIELDS[$i] = i; }; next; }
{ acc += $FIELDS["bar"] }
END { ... }
```

Which is not only a bit of a mouthful, but it also defeats frawk's [projection pushdown](https://github.com/ezrosent/frawk/blob/master/src/pushdown.rs) analysis (we'll always read in all fields because the first action uses them all). The script should still _work_, but now a key optimization gets turned off.

A couple follow-up questions on syntax,

* What do you think of the `$FIELDS["bar"]` syntax? Too verbose? Too strange? I think I prefer it personally so we don't have "two ways to access a column" but it is not a strong preference at the moment.
* As for getting more adventurous with syntax I don't think $"bar" works either: today it will print `$0` :). We could special-case string literals, but I think more things would break if we did that. 
I was thinking you could use `.` to evoke field access in other languages with something like `.bar` or `$.bar`. Thoughts? The corresponding line in your example would then be `{acc += $.bar}` +/- the `$`. This version of the syntax would preclude dynamic values for column accesses, but we could also have `."bar"`.

I'm currently working on a couple longer-term improvements to frawk, but I have a couple items I plan to get back to in the next couple weeks. One of them (basic data-flow analysis for strings) is a prerequisite for the versions of this feature with dynamic column accesses. I'll follow up here once that's done and see if I can game out the work I'll need to do to finish up.

**Comment by asayers** [comment]
> $FIELDS["bar"]

Ah nice, I didn't think of that.  This has the advantage that it's less magical and easier to explain, plus you get the familiar "$" hint to indicate field access.  Considering the verbosity, perhaps it just needs to be shorter?  `FI` (for "field index") feels quite awky (for better or for worse).

> This version of the syntax would preclude dynamic values for column accesses, but we could also have ."bar".

Another thing to say in favour of quoting is that it allows header names to contain spaces.

PS. The standard-awk boilerplate would also need to fix up NR, like so:

```awk
BEGIN { NR-- }
NR == 0 { for (i=1; i<=NF; i++) { FIELDS[$i] = i; }; next; }
```

**Comment by asayers** [comment]
`$["bar"]` would work - this is syntactically forbidden in standard AWK.

**Comment by ezrosent** [comment]
Thanks for the feedback and suggestions. I'll start preliminary work on this this week and scope out the full implementation. Once the feature is mostly there I'll think more about the syntax. My current preference is for `$FI["column"]` over `$["column"]` but once again I don't strongly dislike any of these options.

**Comment by ezrosent** [comment]
I've got an implementation of this feature using `FI` rather than introducing new syntax in the parse-header branch. I still have some things to clean up but assuming I don't discover any new issues, I'll probably have this merged in the next week or so.

Let me know if you have any objections to `FI`; the current implementation only treats FI specially if header-parsing is enabled. Otherwise, it behaves like a normal variable; that should help avoid nasty errors when porting over existing scripts.

**Comment by asayers** [comment]
Nice, that was quick!  I tested with

* old: `frawk -icsv 'NR==1 { next } { cs[$13] += 1 } END { for (inst in cs) { print inst "\t" cs[inst] } }'`
* new: `frawk -icsv -H '{ cs[$FI["Inst"]] += 1 } END { for (inst in cs) { print inst "\t" cs[inst] } }'`

They gave the same output :+1:.  It looks like it's a little bit slower with `-H` (although this is using the bytecode interpreter):

```
           old            new            difference (99.9% CI)
sys_time   0.033 ± 0.012  0.033 ± 0.011  [ -14.0% ..  +11.8%]
user_time  0.437 ± 0.024  0.463 ± 0.026  [  +3.7% ..   +8.1%]
wall_time  0.471 ± 0.022  0.496 ± 0.025  [  +3.4% ..   +7.2%]
samples    158            153
```

**Comment by ezrosent** [comment]
Thanks for trying it out! It makes sense to me that things are still a bit slower than using the indexes directly. frawk is still doing a hash table lookup each time, and it also does a little extra copying in the `-H` case as well at the moment.
I'm looking at how easy the latter is to fix, but I don't think the former is going to go anywhere until I add some more generic optimizations to the compiler.

Still, it seems a lot better than doing some more naive syntactic sugar; here's a quick comparison I did taking an average of the "count" field in a csv for each invocation (this is with LLVM):

Baseline:
```
$ time target/release/frawk -icsv 'BEGIN { getline; } { sum += $6; } END { print sum/NR; }' ./x.csv 
95.6998319835511

real	0m4.782s
user	0m4.587s
sys	0m0.196s
```

"Naive" implementation:
```
$ time target/release/frawk -icsv '
BEGIN { getline; for (i=1; i<=NF; ++i) FI[$i]=i; }
{ sum += $FI["count"]; }
END { print sum/NR; }' ./x.csv
95.6998319835511

real	0m10.300s
user	0m10.081s
sys	0m0.220s
```

Using -H:
```
$ time target/release/frawk -icsv -H '{ sum += $FI["count"]; } END { print sum/NR; }' ./x.csv 
95.6998319835511

real	0m6.057s
user	0m5.805s
sys	0m0.252s
```

The `-H` version is more ergonomic, and it eliminates most of the overhead we see when we do simple rewriting.

**Comment by asayers** [comment]
Just speaking for myself, I'm perfectly happy to pay a small amount of performance to get `FI` in my awk scripts.  Looking forward to seeing it merged!

**Comment by ezrosent** [comment]
It's merged! going to close this issue. Please reopen if I've missed something.
